name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |-
                    python -m pip install --upgrade pip
                    python -m pip install --upgrade setuptools twine wheel

            - name: Build
              run: python setup.py sdist bdist_wheel
